using Content.Shared.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AccessibilityTab : Control
{
    public AccessibilityTab()
    {
        RobustXamlLoader.Load(this);

        Control.AddOptionCheckBox(CCVars.ChatEnableColorName, EnableColorNameCheckBox);
        Control.AddOptionCheckBox(CCVars.AccessibilityColorblindFriendly, ColorblindFriendlyCheckBox);
        Control.AddOptionCheckBox(CCVars.ReducedMotion, ReducedMotionCheckBox);
        Control.AddOptionPercentSlider(CCVars.ScreenShakeIntensity, ScreenShakeIntensitySlider);
        Control.AddOptionPercentSlider(CCVars.ChatWindowOpacity, ChatWindowOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleTextOpacity, SpeechBubbleTextOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleSpeakerOpacity, SpeechBubbleSpeakerOpacitySlider);
        Control.AddOptionPercentSlider(CCVars.SpeechBubbleBackgroundOpacity, SpeechBubbleBackgroundOpacitySlider);

        Control.AddOptionCheckBox(CCVars.AccessibilityClientCensorNudity, CensorNudityCheckBox);

        Control.Initialize();
    }

    public void Relocalize()
    {
        EnableColorNameCheckBox.Text = Loc.GetString("ui-options-enable-color-name");
        ColorblindFriendlyCheckBox.Text = Loc.GetString("ui-options-colorblind-friendly");
        ReducedMotionCheckBox.Text = Loc.GetString("ui-options-reduced-motion");
        ScreenShakeIntensitySlider.Title = Loc.GetString("ui-options-screen-shake-intensity");
        ChatWindowOpacitySlider.Title = Loc.GetString("ui-options-chat-window-opacity");
        SpeechBubbleTextOpacitySlider.Title = Loc.GetString("ui-options-speech-bubble-text-opacity");
        SpeechBubbleSpeakerOpacitySlider.Title = Loc.GetString("ui-options-speech-bubble-speaker-opacity");
        SpeechBubbleBackgroundOpacitySlider.Title = Loc.GetString("ui-options-speech-bubble-background-opacity");
        CensorNudityCheckBox.Text = Loc.GetString("ui-options-censor-nudity");
        Control.RefreshLocalization();
    }
}

