using System;
using System.Linq;
using Content.Client.Localization;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Actions.Windows;

[GenerateTypedNameReferences]
public sealed partial class ActionsWindow : DefaultWindow, ILocalizedControl
{
    public MultiselectOptionButton<Filters> FilterButton { get; private set; }

    /// <summary>
    /// Whether the displayed actions or search filter needs updating.
    /// </summary>
    public bool UpdateNeeded;

    public ActionsWindow()
    {
        RobustXamlLoader.Load(this);

        SearchContainer.AddChild(FilterButton = new MultiselectOptionButton<Filters>());
        Relocalize();
    }

    public void Relocalize()
    {
        var selected = FilterButton.SelectedKeys.ToArray();

        Title = Loc.GetString("ui-actionmenu-title");
        SearchBar.PlaceHolder = Loc.GetString("ui-actionmenu-search-bar-placeholder-text");
        ClearButton.Text = Loc.GetString("ui-actionmenu-clear-button");
        FilterButton.Label = Loc.GetString("ui-actionmenu-filter-button");
        FilterButton.Clear();

        foreach (var filter in Enum.GetValues<Filters>())
        {
            FilterButton.AddItem(Loc.GetString($"ui-actionmenu-{filter.ToString().ToLower()}"), filter);
        }

        foreach (var filter in selected)
        {
            FilterButton.SelectKey(filter);
        }
    }

    public enum Filters
    {
        Enabled,
        Item,
        Innate,
        Instant,
        Targeted
    }
}
