- type: department
  id: CivilianNC
  name: Гражданские
  description: department-CivilianNC-description
  color: "#999999"
  roles:
    - NCCitizen
    - Reaper
    - Fixer
    - EdgeRunnerSolo

- type: department
  id: NCPD
  name: Night City Police Department
  description: department-NCPD-description
  color: "#1e90ff"
  roles:
    - NCPDChief
    - NCPDCommander
    - NCPDInspector
    - NCPDLieutenant
    - NCPDSergeant
    - NCPDOfficer
    - MaxTacCommander
    - MaxTacEraser

- type: department
  id: TraumaTeam
  name: Отдление TraumaTeam
  description: department-TraumaTeam-description
  color: "#e74c3c"
  roles:
    - TraumaTeamChief
    - TraumaTeamDoctor
    - TraumaTeamParamedic
    - TraumaTeamOperative
    - TraumaTeamCoroner
    - TraumaTeamPsych
    - TraumaTeamIntern

- type: department
  id: Biotechnica
  name: Отделение Biotechnica
  description: department-Biotechnica-description
  color: "#2ecc71"
  roles:
    - BiotechnicaChief
    - BiotechnicaOperativeLead
    - BiotechnicaOperative
    - BiotechnicaBotanist
    - BiotechnicaMedTech
    - BiotechnicaTech
    - BiotechnicaParamedic

- type: department
  id: Jiraff
  name: Корпорация Zhirafa
  description: department-Biotechnica-description
  color: "#2ecc71"
  roles:
    - ZhirafaJanitor
