- type: department
  id: CivilianNC
  name: department-name-CivilianNC
  description: department-desc-CivilianNC
  color: "#999999"
  roles:
    - NCCitizen
    - Reaper
    - Fixer
    - EdgeRunnerSolo
    - CafeOwner
    - RestaurantOwner

- type: department
  id: NCPD
  name: department-name-NCPD
  description: department-desc-NCPD
  color: "#1e90ff"
  roles:
    - NCPDChief
    - NCPDCommander
    - NCPDInspector
    - NCPDLieutenant
    - NCPDSergeant
    - NCPDOfficer
    - MaxTacCommander
    - MaxTacEraser

- type: department
  id: TraumaTeam
  name: department-name-TraumaTeam
  description: department-desc-TraumaTeam
  color: "#e74c3c"
  roles:
    - TraumaTeamChief
    - TraumaTeamDoctor
    - TraumaTeamParamedic
    - TraumaTeamOperative
    - TraumaTeamCoroner
    - TraumaTeamPsych
    - TraumaTeamIntern

- type: department
  id: Biotechnica
  name: department-name-Biotechnica
  description: department-desc-Biotechnica
  color: "#2ecc71"
  roles:
    - BiotechnicaChief
    - BiotechnicaOperativeLead
    - BiotechnicaOperative
    - BiotechnicaBotanist
    - BiotechnicaMedTech
    - BiotechnicaTech
    - BiotechnicaParamedic

- type: department
  id: Jiraff
  name: department-name-Jiraff
  description: department-desc-Jiraff
  color: "#2ecc71"
  roles:
    - ZhirafaJanitor
