using Content.Client.Localization;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.MenuBar.Widgets
{
    [GenerateTypedNameReferences]
    public sealed partial class GameTopMenuBar : UIWidget, ILocalizedControl
    {
        public GameTopMenuBar()
        {
            RobustXamlLoader.Load(this);
            Relocalize();
        }

        public void Relocalize()
        {
            EscapeButton.ToolTip = Loc.GetString("game-hud-open-escape-menu-button-tooltip");
            GuidebookButton.ToolTip = Loc.GetString("game-hud-open-guide-menu-button-tooltip");
            CharacterButton.ToolTip = Loc.GetString("game-hud-open-character-menu-button-tooltip");
            EmotesButton.ToolTip = Loc.GetString("game-hud-open-emotions-menu-button-tooltip");
            CraftingButton.ToolTip = Loc.GetString("game-hud-open-crafting-menu-button-tooltip");
            ActionButton.ToolTip = Loc.GetString("game-hud-open-actions-menu-button-tooltip");
            LanguageButton.ToolTip = Loc.GetString("game-hud-open-language-menu-button-tooltip");
            AdminButton.ToolTip = Loc.GetString("game-hud-open-admin-menu-button-tooltip");
            SandboxButton.ToolTip = Loc.GetString("game-hud-open-sandbox-menu-button-tooltip");
            AHelpButton.ToolTip = Loc.GetString("ui-options-function-open-a-help");
        }
    }
}
