- type: job
  id: BiotechnicaParamedic
  name: job-name-biotechnica-paramedic
  description: job-description-biotechnica-paramedic
  playTimeTracker: JobBiotechnicaParamedic
  weight: 60
  salary: 150
  icon: "JobIconBiotechParamed"
  startingGear: BiotechnicaParamedicGear
  access:
    - Biotech_MedTech
    - Biotech_Operative
    - Biotech_Staff
    - Biotech_General
    - NC_General

- type: startingGear
  id: BiotechnicaParamedicGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitBiotechnica
    back: ClothingBackpackBiotechnica
    shoes: ClothingShoesColorWhite
    head: ClothingHeadHatBeretSeniorPhysician
    eyes: ClothingEyesGlassesSunglasses
    id: BiotechnicaParamedicPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLabCmo
