using Content.Client.Localization;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Character.Windows;

[GenerateTypedNameReferences]
public sealed partial class CharacterWindow : DefaultWindow, ILocalizedControl
{
    public CharacterWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Relocalize()
    {
        Title = Loc.GetString("character-info-title");
        ObjectivesLabel.Text = Loc.GetString("character-info-objectives-label");
        RolePlaceholder.PlaceholderText = Loc.GetString("character-info-roles-antagonist-text");
    }
}
