- type: job
  id: NCBooster
  name: job-name-booster
  description: job-description-booster
  playTimeTracker: JobNCBooster
  icon: "JobIconCivilCitizen"
  salary: 0
  startingGear: NCBoosterGear

- type: startingGear
  id: NCBoosterGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorGrey
    shoes: ClothingShoesColorBlack
