- type: job
  id: EdgeRunnerSolo
  name: Эджраннер
  description: job-description-edgerunner
  playTimeTracker: JobEdgeRunnerSolo
  salary: 0
  icon: "JobIconCivilEdgerunner"
  access:
    - NC_General
    - EdgeRunner
  startingGear: EdgeRunnerSoloGear

- type: startingGear
  id: EdgeRunnerSoloGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitColorBlack
    back: ClothingBackpackSatchelSecurity
    shoes: ClothingShoesBootsCombat
    id: EdgeRunnerPDA
    gloves: ClothingHandsGlovesColorBlack
    outerClothing: ClothingOuterArmorBasic
