using Content.Client.Stylesheets;
using Content.Client.UserInterface.Fragments;
using Content.Shared._NC.CitiNet.Components;
using Content.Shared._NC.CitiNet.Store;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client._NC.CitiNet.UI.CorporateSupply;

[GenerateTypedNameReferences]
public sealed partial class CorporateSupplySiteUi : PanelContainer
{
    public event Action<string, string, int>? OnBuy;

    public CorporateSupplySiteUi()
    {
        RobustXamlLoader.Load(this);
        Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetNightCity;
    }

    public void UpdateState(CitiNetStoreUpdateState state)
    {
        FundsLabel.Text = $"CORP FUNDS: {state.Balance} ED";
        DataLabel.Text = $"DATA: {state.DataBalance}";
        StatusLabel.Text = state.UsesCorporateAccount
            ? "LINK STATUS: MAIN BASE AUTHORIZED"
            : "LINK STATUS: NO CORPORATE ACCOUNT ROUTE";

        Listings.RemoveAllChildren();

        foreach (var category in state.Categories)
        {
            Listings.AddChild(new Label
            {
                Text = category.Name.ToUpperInvariant(),
                StyleClasses = { "NightCityGlowText" },
                Margin = new Thickness(0, 8, 0, 2)
            });

            foreach (var entry in category.Entries)
            {
                AddListingRow(state, entry);
            }
        }
    }

    private void AddListingRow(CitiNetStoreUpdateState state, CitiNetStoreEntryData entry)
    {
        var isOutOfStock = entry.RemainingCount.HasValue && entry.RemainingCount.Value <= 0;

        var row = new PanelContainer
        {
            StyleClasses = { "NightCityPanelDark" },
            MinHeight = 72,
            Margin = new Thickness(0, 2)
        };

        if (isOutOfStock)
            row.Modulate = Color.FromHex("#333333");

        var hBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(8)
        };

        var icon = new EntityPrototypeView
        {
            SetSize = new Vector2(48, 48),
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(0, 0, 8, 0)
        };
        icon.SetPrototype(entry.ProtoId);
        hBox.AddChild(icon);

        var details = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true,
            VerticalAlignment = VAlignment.Center
        };

        details.AddChild(new Label
        {
            Text = entry.Name.ToUpperInvariant(),
            StyleClasses = { "NightCityGlowText" }
        });
        details.AddChild(new Label
        {
            Text = entry.Description,
            StyleClasses = { "NightCityMutedText" },
            ClipText = true
        });

        if (entry.RemainingCount.HasValue)
        {
            details.AddChild(new Label
            {
                Text = isOutOfStock ? "STOCK: DEPLETED" : $"STOCK: {entry.RemainingCount.Value}",
                StyleClasses = { isOutOfStock ? "NightCityStatusDanger" : "NightCityStatusGood" }
            });
        }

        hBox.AddChild(details);

        var amount = 1;
        var amountBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            VerticalAlignment = VAlignment.Center,
            Margin = new Thickness(8, 0)
        };
        var minusButton = new Button
        {
            Text = "-",
            MinSize = new Vector2(24, 24),
            Disabled = isOutOfStock,
            StyleClasses = { "NightCityButton" }
        };
        var amountLabel = new Label
        {
            Text = "1",
            MinWidth = 30,
            HorizontalAlignment = HAlignment.Center
        };
        var plusButton = new Button
        {
            Text = "+",
            MinSize = new Vector2(24, 24),
            Disabled = isOutOfStock,
            StyleClasses = { "NightCityButton" }
        };

        var priceLabel = new Label
        {
            VerticalAlignment = VAlignment.Center,
            MinWidth = 128,
            Margin = new Thickness(8, 0),
            StyleClasses = { "NightCityStatusWarning" }
        };
        var orderButton = new Button
        {
            MinWidth = 112,
            VerticalAlignment = VAlignment.Center,
            StyleClasses = { "NightCityButton" }
        };

        void RefreshControls()
        {
            var totalPrice = entry.Price * amount;
            var totalData = entry.DataPrice * amount;
            var canAfford = state.Balance >= totalPrice && state.DataBalance >= totalData;

            priceLabel.Text = $"{totalPrice} ED + {totalData} DATA";
            orderButton.Text = isOutOfStock ? "DEPLETED" : canAfford ? "REQUEST" : "DENIED";
            orderButton.Disabled = isOutOfStock || !canAfford || !state.UsesCorporateAccount;
        }

        minusButton.OnPressed += _ =>
        {
            if (amount <= 1)
                return;

            amount--;
            amountLabel.Text = amount.ToString();
            RefreshControls();
        };

        plusButton.OnPressed += _ =>
        {
            if (entry.RemainingCount.HasValue && amount >= entry.RemainingCount.Value)
                return;

            amount++;
            amountLabel.Text = amount.ToString();
            RefreshControls();
        };

        amountBox.AddChild(minusButton);
        amountBox.AddChild(amountLabel);
        amountBox.AddChild(plusButton);

        if (!isOutOfStock)
            hBox.AddChild(amountBox);

        orderButton.OnPressed += _ => OnBuy?.Invoke(entry.Id, entry.ProtoId, amount);
        RefreshControls();

        hBox.AddChild(priceLabel);
        hBox.AddChild(orderButton);
        row.AddChild(hBox);
        Listings.AddChild(row);
    }
}

public sealed partial class CorporateSupplySiteUiFragment : UIFragment, ICitiNetSiteFragment
{
    private CorporateSupplySiteUi? _control;

    public override Control GetUIFragmentRoot() => _control!;

    public override void Setup(BoundUserInterface userInterface, EntityUid? fragmentOwner)
    {
        _control = new CorporateSupplySiteUi();
        _control.OnBuy += (catId, protoId, amount) =>
            userInterface.SendMessage(new CitiNetStoreBuyRequestMessage(catId, protoId, amount));

        userInterface.SendMessage(new CitiNetStoreRequestDataMessage());
    }

    public override void UpdateState(BoundUserInterfaceState state)
    {
        if (state is CitiNetStoreUpdateState storeState)
            _control?.UpdateState(storeState);
    }

    public void ReceiveMessage(BoundUserInterfaceMessage message)
    {
    }
}
