- type: job
  id: NCPDOfficer
  name: job-name-ncpd-officer
  description: job-description-ncpd-officer
  playTimeTracker: JobNCPDOfficer
  weight: 40
  salary: 120
  icon: "JobIconNCPDPolice"
  startingGear: NCPDOfficerGear
  supervisors: Старший патрульный
  access:
    - NCPD_Patrol
    - NC_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: MapBeacon
      group: NCPD
      color: "#ffaa00"
      icon: /Textures/Interface/VerbIcons/star-solid-yellow.svg.192dpi.png
      visibleInWorld: false

- type: startingGear
  id: NCPDOfficerGear
  equipment:
    jumpsuit: ClothingUniformNSPDNormis
    back: ClothingBackpackSecurity
    shoes: ClothingShoesBootsJack
    eyes: ClothingEyesGlassesSecurityVisor
    head: ClothingHeadHelmetBasic
    id: NCPDOfficerPDA
    belt: ClothingBeltSecurityFilled
    outerClothing: ClothingOuterArmorBasic
