using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.PDA;

[GenerateTypedNameReferences]
public sealed partial class PdaNavigationButton : ContainerButton
{
    private const string DefaultInactiveBgColor = "#202023";
    private const string DefaultActiveBgColor = "#25252a";
    private const string DefaultInactiveFgColor = "#5a5a5a";
    private const string DefaultActiveFgColor = "#FFFFFF";
    private const string DefaultBorderColor = "#5a5a5a";

    private bool _isCurrent;
    private bool _isActive = true;

    private Thickness _borderThickness = new(0, 0, 0, 2);
    private Thickness _currentTabBorderThickness = new(2, 0, 2, 0);

    private readonly StyleBoxFlat _styleBox = new()
    {
        BackgroundColor = Color.FromHex(DefaultInactiveBgColor),
        BorderColor = Color.FromHex(DefaultBorderColor),
        BorderThickness = new Thickness(0, 0, 0, 2)
    };

    public string InactiveBgColor { get; set; } = DefaultInactiveBgColor;
    public string ActiveBgColor { get; set; } = DefaultActiveBgColor;
    public string InactiveFgColor { get; set; } = DefaultInactiveFgColor;
    public string ActiveFgColor { get; set; } = DefaultActiveFgColor;
    public string BorderColor { get; set; } = DefaultBorderColor;

    public SpriteSpecifier? IconTexture
    {
        set
        {
            Icon.Visible = value != null;
            Label.Visible = value == null;

            if (value is not null)
                Icon.SetFromSpriteSpecifier(value);
        }
    }

    public Vector2 IconScale
    {
        get => Icon.DisplayRect.TextureScale;
        set => Icon.DisplayRect.TextureScale = value;
    }

    public string? LabelText
    {
        get => Label.Text;
        set => Label.Text = value;
    }

    /// <summary>
    /// Sets the border thickness when the tab is not the currently active one
    /// </summary>
    public Thickness BorderThickness
    {
        get => _borderThickness;
        set
        {
            _borderThickness = value;
            _styleBox.BorderThickness = _isCurrent ? _currentTabBorderThickness : value;
        }
    }

    /// <summary>
    /// Sets the border thickness when this tab is the currently active tab
    /// </summary>
    public Thickness CurrentTabBorderThickness
    {
        get => _currentTabBorderThickness;
        set
        {
            _currentTabBorderThickness = value;
            _styleBox.BorderThickness = _isCurrent ? value : _borderThickness;
        }
    }

    public bool IsCurrent
    {
        get => _isCurrent;
        set
        {
            _isCurrent = value;
            RefreshVisualState();
        }
    }

    public bool IsActive
    {
        get => _isActive;
        set
        {
            _isActive = value;
            RefreshVisualState();
        }
    }

    public PdaNavigationButton()
    {
        RobustXamlLoader.Load(this);
        Background.PanelOverride = _styleBox;
        RefreshVisualState();
    }

    /// <summary>
    /// Applies a Night City palette to PDA shell tabs while preserving the original layout behavior.
    /// </summary>
    public void ApplyNightCityTheme(bool enabled)
    {
        if (enabled)
        {
            InactiveBgColor = "#0c1118";
            ActiveBgColor = "#111b24";
            InactiveFgColor = "#7b8b99";
            ActiveFgColor = "#00f2ff";
            BorderColor = "#00f2ff";
        }
        else
        {
            InactiveBgColor = DefaultInactiveBgColor;
            ActiveBgColor = DefaultActiveBgColor;
            InactiveFgColor = DefaultInactiveFgColor;
            ActiveFgColor = DefaultActiveFgColor;
            BorderColor = DefaultBorderColor;
        }

        RefreshVisualState();
    }

    /// <summary>
    /// Rebuilds the tab chrome after a state or palette change.
    /// </summary>
    private void RefreshVisualState()
    {
        _styleBox.BackgroundColor = Color.FromHex(_isCurrent ? ActiveBgColor : InactiveBgColor);
        _styleBox.BorderColor = Color.FromHex(BorderColor);
        _styleBox.BorderThickness = _isCurrent ? CurrentTabBorderThickness : BorderThickness;

        var foreground = Color.FromHex(_isActive ? ActiveFgColor : InactiveFgColor);
        Icon.Modulate = foreground;
        Label.FontColorOverride = foreground;
    }
}
