using System;
using System.Linq;
using Content.Client.Stylesheets;
using Content.Shared._NC.CitiNet;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._NC.CitiNet.UI;

[GenerateTypedNameReferences]
public sealed partial class CitiNetUiFragment : BoxContainer
{
    private enum ActionMode : byte
    {
        None,
        StartP2P,
        GroupAction,
        InviteToChannel
    }

    public Action<CitiNetUiMessageType, string?, string?>? OnSendMessage;

    private int _currentTab = 1;
    private CitiNetUiState? _lastState;
    private ActionMode _actionMode = ActionMode.None;
    private string? _actionChannelId;
    private float _fade;

    private static readonly Color ColorGood = Color.FromHex("#4ff3ff");
    private static readonly Color ColorGoodDim = Color.FromHex("#2a8f96");
    private static readonly Color ColorAlertRed = Color.FromHex("#ff5a5a");
    private static readonly Color ColorCyberBlue = Color.FromHex("#7ad7ff");
    private static readonly Color ColorWarning = Color.FromHex("#ffb347");
    private static readonly Color ColorDarkGrey = Color.FromHex("#5f6b76");
    private static readonly Color ColorReadableSlate = Color.FromHex("#9fb4c4");
    private static readonly Color ColorReadableCyan = Color.FromHex("#9cecff");
    private static readonly Color ColorTrauma = Color.FromHex("#63f5c3");

    private const int ListWidthDefault = 250;
    private const int ListWidthContacts = 320;

    public CitiNetUiFragment()
    {
        RobustXamlLoader.Load(this);
        Stylesheet = IoCManager.Resolve<IStylesheetManager>().SheetNightCity;

        MenuDirectCallsBtn.OnPressed += _ => SwitchTab(0);
        MenuChatRoomsBtn.OnPressed += _ => SwitchTab(1);
        MenuDataPoolBtn.OnPressed += _ => SwitchTab(2);
        MenuContactsBtn.OnPressed += _ => SwitchTab(3);

        ChatSendButton.OnPressed += _ =>
        {
            var text = ChatInput.Text.Trim();
            if (string.IsNullOrEmpty(text))
                return;

            if (_currentTab == 0 && _lastState?.CurrentContactNumber != null)
                OnSendMessage?.Invoke(CitiNetUiMessageType.SendCallMessage, null, text);
            else if (_currentTab == 1 && _lastState?.CurrentChannelId != null)
                OnSendMessage?.Invoke(CitiNetUiMessageType.SendBBSMessage, null, text);
            else if (_currentTab == 2 && _lastState is { InGroup: true })
                OnSendMessage?.Invoke(CitiNetUiMessageType.SendGroupMessage, null, text);

            ChatInput.Text = string.Empty;
        };

        ActionButton.OnPressed += HandleActionButton;

        CallDialButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.InitiateCall, null, null);
        CallAcceptButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.AcceptCall, null, null);
        CallDeclineButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.DeclineCall, null, null);
        CallHangUpButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.HangUp, null, null);
        CallPingLocationButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.PingLocation, null, null);
        CallJoinVoiceButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.JoinGroupVoice, null, null);
        CallLeaveVoiceButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.LeaveGroupVoice, null, null);

        PasswordSubmitBtn.OnPressed += _ =>
        {
            var text = PasswordInput.Text.Trim();
            if (!string.IsNullOrEmpty(text) && _lastState?.CurrentChannelId != null)
            {
                OnSendMessage?.Invoke(CitiNetUiMessageType.JoinChannel, _lastState.CurrentChannelId, text);
                PasswordInput.Text = string.Empty;
            }
        };

        SwitchTab(0, false);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        // Keep the fragment responsive without introducing heavy animation code.
        _fade = MathHelper.Lerp(_fade, 1f, args.DeltaSeconds * 10f);
        ModulateSelfOverride = Color.White.WithAlpha(_fade);
    }

    private void SetMenuButtonState(Button button, bool active)
    {
        // The active route stays bright while inactive tabs remain readable but subdued.
        button.Modulate = active ? Color.White : ColorGoodDim;
    }

    private static Button CreateNightCityButton(string text, Color modulate, string styleClass = "NightCityButton")
    {
        return new Button
        {
            Text = text,
            Modulate = modulate,
            HorizontalAlignment = HAlignment.Left,
            HorizontalExpand = true,
            Margin = new Thickness(0, 0, 0, 4),
            StyleClasses = { styleClass }
        };
    }

    private static string Escape(string value)
    {
        return FormattedMessage.EscapeText(value);
    }

    /// <summary>
    /// RichTextLabel ignores color markup when text is assigned directly, so Night City labels must use formatted messages.
    /// </summary>
    private static void SetMarkup(RichTextLabel label, string markupText)
    {
        label.SetMessage(FormattedMessage.FromMarkupOrThrow(markupText));
    }

    private int TabToInt(CitiNetTab tab) => tab switch
    {
        CitiNetTab.P2P => 0,
        CitiNetTab.BBS => 1,
        CitiNetTab.Group => 2,
        CitiNetTab.Contacts => 3,
        _ => 0
    };

    private CitiNetTab? IntToTab(int tab) => tab switch
    {
        0 => CitiNetTab.P2P,
        1 => CitiNetTab.BBS,
        2 => CitiNetTab.Group,
        3 => CitiNetTab.Contacts,
        _ => null
    };

    private void SwitchTab(int tab, bool notifyServer = true)
    {
        _currentTab = tab;

        if (notifyServer)
        {
            var serverTab = IntToTab(tab);
            if (serverTab != null)
                OnSendMessage?.Invoke(CitiNetUiMessageType.SelectTab, null, serverTab.Value.ToString());
        }

        SetMenuButtonState(MenuDirectCallsBtn, tab == 0);
        SetMenuButtonState(MenuChatRoomsBtn, tab == 1);
        SetMenuButtonState(MenuDataPoolBtn, tab == 2);
        SetMenuButtonState(MenuContactsBtn, tab == 3);

        ListContainer.RemoveAllChildren();
        ContentMessagesContainer.RemoveAllChildren();
        ActionControlsPanel.Visible = false;
        PasswordPanel.Visible = false;
        ChatInputPanel.Visible = false;
        CallControlsPanel.Visible = false;
        _actionMode = ActionMode.None;
        _actionChannelId = null;

        if (_lastState != null)
            UpdateUIFields(_lastState);
    }

    private void HandleActionButton(BaseButton.ButtonEventArgs args)
    {
        var input = ActionInput.Text.Trim();

        switch (_actionMode)
        {
            case ActionMode.StartP2P:
                if (!string.IsNullOrEmpty(input))
                {
                    OnSendMessage?.Invoke(CitiNetUiMessageType.StartChat, input, null);
                    ActionInput.Text = string.Empty;
                }
                break;

            case ActionMode.GroupAction:
                if (_lastState != null && !_lastState.InGroup)
                {
                    OnSendMessage?.Invoke(CitiNetUiMessageType.CreateGroup, null, null);
                }
                else if (!string.IsNullOrEmpty(input))
                {
                    OnSendMessage?.Invoke(CitiNetUiMessageType.InviteToGroup, input, null);
                    ActionInput.Text = string.Empty;
                }
                break;

            case ActionMode.InviteToChannel:
                if (!string.IsNullOrEmpty(input) && !string.IsNullOrEmpty(_actionChannelId))
                {
                    OnSendMessage?.Invoke(CitiNetUiMessageType.InviteToChannel, input, _actionChannelId);
                    ActionInput.Text = string.Empty;
                }
                break;
        }
    }

    public void UpdateState(CitiNetUiState state)
    {
        if (_lastState == null || _lastState.ActiveTab != state.ActiveTab)
        {
            var newTab = TabToInt(state.ActiveTab);
            if (_currentTab != newTab)
                SwitchTab(newTab, false);
        }

        _lastState = state;

        SetMarkup(HeaderLabel, $"[color={ColorReadableSlate.ToHex()}]{Escape(Loc.GetString("citinet-ui-neural-line", ("number", state.OwnNumber)))}[/color]");
        SetMarkup(NetworkStatusLabel, state.HasRelay
            ? $"[color={ColorGood.ToHex()}]{Escape(Loc.GetString("citinet-ui-network-link-stable"))}[/color]"
            : $"[color={ColorAlertRed.ToHex()}]{Escape(Loc.GetString("citinet-ui-network-relay-lost"))}[/color]");
        SetMarkup(OnlineStatusLabel, state.HasRelay
            ? $"[color={ColorGood.ToHex()}]{Escape(Loc.GetString("citinet-ui-status-online"))}[/color]"
            : $"[color={ColorAlertRed.ToHex()}]{Escape(Loc.GetString("citinet-ui-status-offline"))}[/color]");
        SetMarkup(UsernameLabel, $"[color={ColorReadableCyan.ToHex()}]{Escape(Loc.GetString("citinet-ui-agent-profile", ("number", state.OwnNumber)))}[/color]");

        UpdateUIFields(state);
    }

    private void UpdateUIFields(CitiNetUiState state)
    {
        ListContainer.RemoveAllChildren();
        ContentMessagesContainer.RemoveAllChildren();
        ActionControlsPanel.Visible = false;
        CallControlsPanel.Visible = false;
        PasswordPanel.Visible = false;
        ChatInputPanel.Visible = false;
        _actionMode = ActionMode.None;
        _actionChannelId = null;

        switch (_currentTab)
        {
            case 0:
                RenderDirectCalls(state);
                break;
            case 1:
                RenderChatRooms(state);
                break;
            case 2:
                RenderDataPool(state);
                break;
            case 3:
                RenderContacts(state);
                break;
        }
    }

    private void RenderDirectCalls(CitiNetUiState state)
    {
        ApplyScreenHeading(Loc.GetString("citinet-ui-screen-calls"), Loc.GetString("citinet-ui-subtitle-contact-routing"));
        ListTitleLabel.Text = Loc.GetString("citinet-ui-list-direct-calls");
        ListSubtitleLabel.Text = Loc.GetString("citinet-ui-subtitle-contact-routing");
        SetMarkup(ContentHeaderLabel, $"[color={ColorGood.ToHex()}]{Escape(Loc.GetString("citinet-ui-header-p2p-communication"))}[/color]");
        SetMarkup(ContentSubHeaderLabel, $"[color={ColorReadableSlate.ToHex()}]{Escape(Loc.GetString("citinet-ui-copy-direct-messages-voice"))}[/color]");
        ConfigurePanelWidths(false);

        ActionControlsPanel.Visible = true;
        ActionInput.Visible = true;
        ActionInput.PlaceHolder = Loc.GetString("citinet-ui-placeholder-new-agent-number");
        ActionButton.Text = Loc.GetString("citinet-ui-action-start-chat");
        _actionMode = ActionMode.StartP2P;

        if (state.Contacts.Count == 0)
        {
            AddListEntry(Loc.GetString("citinet-ui-empty-no-active-contacts"), ColorDarkGrey);
        }
        else
        {
            foreach (var contact in state.Contacts)
            {
                var isCurrent = contact.Number == state.CurrentContactNumber;
                var color = isCurrent ? ColorGood : ColorCyberBlue;
                var prefix = isCurrent ? ">" : " ";
                var button = CreateNightCityButton($"{prefix} {Escape(contact.Name)} (#{contact.Number})", color);
                button.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.StartChat, contact.Number, null);
                ListContainer.AddChild(button);
            }
        }

        if (state.CurrentContactNumber == null)
        {
            AddMessage($"[color={ColorDarkGrey.ToHex()}]{Escape(Loc.GetString("citinet-ui-hint-select-contact"))}[/color]");
            return;
        }

        foreach (var msg in state.CallMessages)
        {
            var color = msg.IsSystem ? ColorAlertRed : ColorCyberBlue;
            AddTimestampedMessage(color, msg.Timestamp, msg.SenderName, msg.Content);
        }

        ChatInputPanel.Visible = true;
        CallControlsPanel.Visible = true;

        CallDialButton.Visible = state.CallState == CitiNetCallState.None;
        CallPingLocationButton.Visible = true;
        CallAcceptButton.Visible = state.CallState == CitiNetCallState.Incoming;
        CallDeclineButton.Visible = state.CallState == CitiNetCallState.Incoming;
        CallHangUpButton.Visible = state.CallState is CitiNetCallState.Active or CitiNetCallState.Ringing;
        CallJoinVoiceButton.Visible = false;
        CallLeaveVoiceButton.Visible = false;

        SetMarkup(CallControlsStatusLabel, state.CallState switch
        {
            CitiNetCallState.Active => $"[color={ColorGood.ToHex()}]{Escape(Loc.GetString("citinet-ui-voice-connected"))}[/color]",
            CitiNetCallState.Ringing => $"[color={ColorWarning.ToHex()}]{Escape(Loc.GetString("citinet-ui-voice-ringing"))}[/color]",
            CitiNetCallState.Incoming => $"[color={ColorAlertRed.ToHex()}]{Escape(Loc.GetString("citinet-ui-voice-incoming"))}[/color]",
            _ => $"[color={ColorDarkGrey.ToHex()}]{Escape(Loc.GetString("citinet-ui-voice-idle"))}[/color]"
        });
    }

    private void RenderChatRooms(CitiNetUiState state)
    {
        ApplyScreenHeading(Loc.GetString("citinet-ui-screen-chats"), Loc.GetString("citinet-ui-subtitle-available-networks"));
        ListTitleLabel.Text = Loc.GetString("citinet-ui-list-chat-rooms");
        ListSubtitleLabel.Text = Loc.GetString("citinet-ui-subtitle-available-networks");
        SetMarkup(ContentHeaderLabel, $"[color={ColorGood.ToHex()}]{Escape(Loc.GetString("citinet-ui-header-public-secure-bbs"))}[/color]");
        SetMarkup(ContentSubHeaderLabel, $"[color={ColorReadableSlate.ToHex()}]{Escape(Loc.GetString("citinet-ui-copy-channel-feed"))}[/color]");
        ConfigurePanelWidths(false);

        if (state.Channels.Count == 0)
        {
            AddListEntry(Loc.GetString("citinet-ui-empty-no-channels-found"), ColorDarkGrey);
            return;
        }

        foreach (var channel in state.Channels)
        {
            var prefix = state.CurrentChannelId == channel.Id ? ">" : channel.IsJoined ? "+" : " ";
            var button = CreateNightCityButton($"{prefix} {channel.Name}", Color.White);
            button.Modulate = state.CurrentChannelId == channel.Id ? ColorGood : channel.Color;

            button.OnPressed += _ =>
            {
                if (channel.IsJoined || channel.RequiresPassword)
                    OnSendMessage?.Invoke(CitiNetUiMessageType.SelectChannel, channel.Id, null);
                else
                    OnSendMessage?.Invoke(CitiNetUiMessageType.JoinChannel, channel.Id, null);
            };

            ListContainer.AddChild(button);
        }

        var currentChannel = state.Channels.FirstOrDefault(c => c.Id == state.CurrentChannelId);
        if (currentChannel.Id == null)
            return;

        SetMarkup(ContentHeaderLabel, $"[color={currentChannel.Color.ToHex()}]{Escape(currentChannel.Name.ToUpperInvariant())}[/color]");
        SetMarkup(ContentSubHeaderLabel, currentChannel.IsJoined
            ? $"[color={ColorReadableSlate.ToHex()}]{Escape(Loc.GetString("citinet-ui-channel-linked"))}[/color]"
            : $"[color={ColorDarkGrey.ToHex()}]{Escape(Loc.GetString("citinet-ui-channel-access-not-established"))}[/color]");

        if (currentChannel.RequiresPassword && !currentChannel.IsJoined)
        {
            PasswordPanel.Visible = true;
            AddMessage($"[color={ColorAlertRed.ToHex()}]{Escape(Loc.GetString("citinet-ui-channel-secured-enter-code"))}[/color]");
            return;
        }

        if (!currentChannel.IsJoined)
            return;

        ChatInputPanel.Visible = true;

        foreach (var msg in state.ChannelMessages)
        {
            AddTimestampedMessage(currentChannel.Color, msg.Timestamp, msg.SenderName, msg.Content);
        }

        if (!currentChannel.CanInvite)
            return;

        ActionControlsPanel.Visible = true;
        ActionInput.Visible = true;
        ActionInput.PlaceHolder = Loc.GetString("citinet-ui-placeholder-agent-number");
        ActionButton.Text = Loc.GetString("citinet-ui-action-invite-to-channel");
        _actionMode = ActionMode.InviteToChannel;
        _actionChannelId = currentChannel.Id;
    }

    private void RenderDataPool(CitiNetUiState state)
    {
        ApplyScreenHeading(Loc.GetString("citinet-ui-screen-pool"), Loc.GetString("citinet-ui-subtitle-tactical-bridge"));
        ListTitleLabel.Text = Loc.GetString("citinet-ui-list-data-pool");
        ListSubtitleLabel.Text = Loc.GetString("citinet-ui-subtitle-tactical-bridge");
        ConfigurePanelWidths(false);

        if (!state.InGroup)
        {
            SetMarkup(ContentHeaderLabel, $"[color={ColorGood.ToHex()}]{Escape(Loc.GetString("citinet-ui-bridge-offline-header"))}[/color]");
            SetMarkup(ContentSubHeaderLabel, $"[color={ColorDarkGrey.ToHex()}]{Escape(Loc.GetString("citinet-ui-copy-no-active-bridge"))}[/color]");
            AddListEntry(Loc.GetString("citinet-ui-bridge-offline-list"), ColorDarkGrey);

            ActionControlsPanel.Visible = true;
            ActionInput.Visible = false;
            ActionButton.Text = Loc.GetString("citinet-ui-action-create-tactical-bridge");
            _actionMode = ActionMode.GroupAction;
            return;
        }

        SetMarkup(ContentHeaderLabel, $"[color={ColorGood.ToHex()}]{Escape(Loc.GetString("citinet-ui-bridge-online-header"))}[/color]");
        SetMarkup(ContentSubHeaderLabel, $"[color={ColorReadableSlate.ToHex()}]{Escape(Loc.GetString("citinet-ui-copy-live-squad-mesh"))}[/color]");
        ActionControlsPanel.Visible = true;
        ActionInput.Visible = true;
        ActionInput.PlaceHolder = Loc.GetString("citinet-ui-placeholder-agent-number");
        ActionButton.Text = Loc.GetString("citinet-ui-action-invite-agent");
        _actionMode = ActionMode.GroupAction;

        ChatInputPanel.Visible = true;
        CallControlsPanel.Visible = true;
        CallPingLocationButton.Visible = true;
        CallAcceptButton.Visible = false;
        CallDeclineButton.Visible = false;
        CallHangUpButton.Visible = false;
        CallJoinVoiceButton.Visible = !state.InGroupVoice;
        CallLeaveVoiceButton.Visible = state.InGroupVoice;

        SetMarkup(CallControlsStatusLabel, state.InGroupVoice
            ? $"[color={ColorGood.ToHex()}]{Escape(Loc.GetString("citinet-ui-group-voice-active"))}[/color]"
            : $"[color={ColorDarkGrey.ToHex()}]{Escape(Loc.GetString("citinet-ui-group-voice-standby"))}[/color]");

        AddListEntry(Loc.GetString("citinet-ui-group-slots", ("count", state.GroupParticipants.Count), ("max", state.MaxGroupParticipants)), ColorCyberBlue);
        foreach (var participant in state.GroupParticipants)
        {
            AddListEntry(
                participant.IsAlive
                    ? Loc.GetString("citinet-ui-group-member-alive", ("name", participant.Name))
                    : Loc.GetString("citinet-ui-group-member-flatline", ("name", participant.Name)),
                participant.IsAlive ? ColorGood : ColorAlertRed);
        }

        var leaveButton = CreateNightCityButton(Loc.GetString("citinet-ui-action-leave-bridge"), Color.White, "NightCityButtonDanger");
        leaveButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.LeaveGroup, null, null);
        ListContainer.AddChild(leaveButton);

        foreach (var msg in state.GroupMessages)
        {
            var color = msg.IsSystem ? ColorAlertRed : ColorWarning;
            AddTimestampedMessage(color, msg.Timestamp, msg.SenderName, msg.Content);
        }
    }

    private void RenderContacts(CitiNetUiState state)
    {
        ApplyScreenHeading(Loc.GetString("citinet-ui-screen-contacts"), Loc.GetString("citinet-ui-subtitle-active-citizens"));
        ListTitleLabel.Text = Loc.GetString("citinet-ui-screen-contacts");
        ListSubtitleLabel.Text = Loc.GetString("citinet-ui-subtitle-active-citizens");
        SetMarkup(ContentHeaderLabel, $"[color={ColorGood.ToHex()}]{Escape(Loc.GetString("citinet-ui-header-directory"))}[/color]");
        SetMarkup(ContentSubHeaderLabel, $"[color={ColorReadableSlate.ToHex()}]{Escape(Loc.GetString("citinet-ui-copy-citizen-directory"))}[/color]");
        ConfigurePanelWidths(true);

        if (state.AllPlayers.Count == 0)
        {
            AddListEntry(Loc.GetString("citinet-ui-empty-no-players-online"), ColorDarkGrey);
        }
        else
        {
            foreach (var player in state.AllPlayers)
            {
                var button = CreateNightCityButton(
                    Loc.GetString("citinet-ui-player-entry", ("name", player.Name), ("number", player.Number)),
                    player.Number == "N/A" ? ColorDarkGrey : ColorCyberBlue);

                if (player.Number != "N/A" && player.Number != state.OwnNumber)
                {
                    button.OnPressed += _ =>
                    {
                        SwitchTab(0, true);
                        OnSendMessage?.Invoke(CitiNetUiMessageType.StartChat, player.Number, null);
                    };
                }

                ListContainer.AddChild(button);
            }
        }

        AddMessage($"[color={ColorGood.ToHex()}]{Escape(Loc.GetString("citinet-ui-emergency-line-online"))}[/color]");
        AddMessage($"[color={ColorCyberBlue.ToHex()}]{Escape(Loc.GetString("citinet-ui-emergency-ncpd"))}[/color]");
        AddMessage($"[color={ColorTrauma.ToHex()}]{Escape(Loc.GetString("citinet-ui-emergency-trauma"))}[/color]");

        var policeButton = CreateNightCityButton(
            state.PoliceCooldown > 0
                ? Loc.GetString("citinet-ui-action-call-police-cooldown", ("seconds", (int) state.PoliceCooldown))
                : Loc.GetString("citinet-ui-action-call-police"),
            Color.White,
            "NightCityButtonDanger");
        policeButton.Disabled = state.PoliceCooldown > 0;
        policeButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.CallPolice, null, null);
        ContentMessagesContainer.AddChild(policeButton);

        var traumaButton = CreateNightCityButton(
            state.TraumaCooldown > 0
                ? Loc.GetString("citinet-ui-action-call-trauma-cooldown", ("seconds", (int) state.TraumaCooldown))
                : Loc.GetString("citinet-ui-action-call-trauma"),
            Color.White);
        traumaButton.Disabled = state.TraumaCooldown > 0;
        traumaButton.OnPressed += _ => OnSendMessage?.Invoke(CitiNetUiMessageType.CallTrauma, null, null);
        ContentMessagesContainer.AddChild(traumaButton);

        AddMessage($"[color={ColorDarkGrey.ToHex()}]{Escape(Loc.GetString("citinet-ui-false-alarms-warning"))}[/color]");
    }

    private void AddListEntry(string text, Color color)
    {
        ListContainer.AddChild(new Label
        {
            Text = text,
            FontColorOverride = color,
            Margin = new Thickness(0, 0, 0, 2)
        });
    }

    private void AddMessage(string markupText)
    {
        var label = new RichTextLabel();
        label.SetMessage(FormattedMessage.FromMarkupOrThrow(markupText));
        ContentMessagesContainer.AddChild(label);
    }

    private void AddTimestampedMessage(Color headerColor, TimeSpan timestamp, string senderName, string content)
    {
        // Robust markup treats square brackets as tag delimiters, so timestamps use parentheses here.
        AddMessage(
            $"[color={headerColor.ToHex()}]({timestamp:hh\\:mm}) {Escape(senderName)}:[/color] {Escape(content)}");
    }

    private void ApplyScreenHeading(string title, string subtitle)
    {
        ScreenTitleLabel.Text = title;
        ScreenSubtitleLabel.Text = subtitle;
    }

    private void ConfigurePanelWidths(bool contactsLayout)
    {
        ListPanel.MinWidth = contactsLayout ? ListWidthContacts : ListWidthDefault;
        DetailPanel.MinWidth = 0;
        ListPanel.HorizontalExpand = false;
        DetailPanel.HorizontalExpand = true;
    }
}
