using Content.Client.Localization;
using Content.Shared.Administration.Managers;
using JetBrains.Annotations;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class ObserveWarningWindow : DefaultWindow, ILocalizedControl
{
    [Dependency] private readonly ISharedAdminManager _adminManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;

    public ObserveWarningWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        var player = _playerManager.LocalSession;

        Relocalize();

        if (player != null && _adminManager.IsAdmin(player))
        {
            ObserveButton.Text = Loc.GetString("observe-as-player");
            ObserveAsAdminButton.Visible = true;
            ObserveAsAdminButton.OnPressed += _ => { this.Close(); };
        }

        ObserveButton.OnPressed += _ => { Close(); };
        NevermindButton.OnPressed += _ => { Close(); };
    }

    public void Relocalize()
    {
        Title = Loc.GetString("observe-warning-window-title");
        NevermindButton.Text = Loc.GetString("observe-nevermind");
        ObserveAsAdminButton.Text = Loc.GetString("observe-as-admin");
        ObserveButton.Text = Loc.GetString("observe-confirm");

        if (ObserveAsAdminButton.Visible)
            ObserveButton.Text = Loc.GetString("observe-as-player");
    }
}
