- type: job
  id: TraumaTeamPsych
  name: КиберПсихолог Trauma Team
  description: Вы — высококвалифицированный специалист с высшим образованием и дипломом психолога...или так всем кажется. Лечите от киберпсихоза при помощи терапии, прописывайте шизам лекарства, а так же утверждайте, что синие человечки - это нормально.
  playTimeTracker: JobTraumaTeamPsych
  weight: 80
  salary: 800
  icon: "JobIconTraumaPsiholog"
  startingGear: TraumaTeamPsychGear
  supervisors: Главный врач Trauma Team
  access:
    - Trauma_Medical
    - Trauma_Morgue
    - NC_General
  special:
  - !type:AddComponentSpecial
    components:
    - type: TraumaSubscriber
      tier: Silver

- type: startingGear
  id: TraumaTeamPsychGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitMedicalDoctor
    back: ClothingBackpackMedical
    shoes: ClothingShoesColorWhite
    id: TraumaTeamPsychPDA
    belt: ClothingBeltMedicalFilled
    outerClothing: ClothingOuterCoatLab
