using Content.Client.Localization;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Sandbox.Windows;

[GenerateTypedNameReferences]
public sealed partial class SandboxWindow : DefaultWindow, ILocalizedControl
{
    public SandboxWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void Relocalize()
    {
        Title = Loc.GetString("sandbox-window-title");
        MapEditingLabel.Text = Loc.GetString("sandbox-window-map-editing-label");
        VisibilityLabel.Text = Loc.GetString("sandbox-window-visibility-label");
        YourCharacterLabel.Text = Loc.GetString("sandbox-window-your-character-label");
        SpawnTilesButton.Text = Loc.GetString("sandbox-window-spawn-tiles-button");
        SpawnEntitiesButton.Text = Loc.GetString("sandbox-window-spawn-entities-button");
        SpawnDecalsButton.Text = Loc.GetString("sandbox-window-spawn-decals-button");
        ToggleLightButton.Text = Loc.GetString("sandbox-window-toggle-lights-button");
        ToggleFovButton.Text = Loc.GetString("sandbox-window-toggle-fov-button");
        ToggleShadowsButton.Text = Loc.GetString("sandbox-window-toggle-shadows-button");
        ToggleSubfloorButton.Text = Loc.GetString("sandbox-window-toggle-subfloor-button");
        ShowLogicPowerButton.Text = Loc.GetString("sandbox-window-show-logic-power-button");
        AiOverlayButton.Text = Loc.GetString("sandbox-window-ai-overlay-button");
        ShowMarkersButton.Text = Loc.GetString("sandbox-window-show-spawns-button");
        ShowBbButton.Text = Loc.GetString("sandbox-window-show-bb-button");
        GiveAghostButton.Text = Loc.GetString("sandbox-window-ghost-button");
        GiveFullAccessButton.Text = Loc.GetString("sandbox-window-grant-full-access-button");
        SuicideButton.Text = Loc.GetString("sandbox-window-toggle-suicide-button");
        RespawnButton.Text = Loc.GetString("sandbox-window-respawn-button");
    }
}
