using Content.Client.UserInterface.Fragments;
using Content.Shared._NC.CitiNet.Store;
using Content.Shared._NC.CitiNet.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client._NC.CitiNet.UI.FixerMarket;

[GenerateTypedNameReferences]
public sealed partial class FixerMarketSiteUi : PanelContainer
{
    public event Action<string, string, Shared._NC.CitiNet.Delivery.DropType>? OnBuy;

    public FixerMarketSiteUi()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(CitiNetStoreUpdateState state)
    {
        if (BalanceLabel != null)
            BalanceLabel.Text = $"BALANCE: {state.Balance} ED";
        
        if (Tabs == null) return;
        Tabs.RemoveAllChildren();

        foreach (var category in state.Categories)
        {
            var scroll = new ScrollContainer { VerticalExpand = true, HScrollEnabled = false };
            var list = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 4, Margin = new Thickness(4) };
            
            foreach (var entry in category.Entries)
            {
                var row = new PanelContainer { StyleClasses = { "PanelBackgroundBaseDark" }, MinHeight = 50, Margin = new Thickness(2) };
                var hBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(8) };
                
                // Icon
                var icon = new EntityPrototypeView { SetSize = new Vector2(32, 32), VerticalAlignment = VAlignment.Center, Margin = new Thickness(0, 0, 8, 0) };
                icon.SetPrototype(entry.ProtoId);
                hBox.AddChild(icon);

                var vBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, HorizontalExpand = true };
                vBox.AddChild(new Label { Text = entry.Name.ToUpper(), StyleClasses = { "LabelHeading" } });
                vBox.AddChild(new Label { Text = entry.Description, FontColorOverride = Color.Gray, ClipText = true });
                
                hBox.AddChild(vBox);
                
                var priceLabel = new Label { Text = $"{entry.Price} ED", VerticalAlignment = VAlignment.Center, Margin = new Thickness(8, 0) };
                hBox.AddChild(priceLabel);

                var buttonsBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, SeparationOverride = 2 };
                
                var buyCorpBtn = new Button { Text = "CORP", MinWidth = 80, ToolTip = "Доставка в защищенный почтомат (PIN-код)" };
                var buyStreetBtn = new Button { Text = "STREET", MinWidth = 80, ToolTip = "Доставка в случайную закладку (без кода)" };

                var catId = entry.Id;
                var protoId = entry.ProtoId;

                buyCorpBtn.OnPressed += _ => OnBuy?.Invoke(catId, protoId, Shared._NC.CitiNet.Delivery.DropType.Corporate);
                buyStreetBtn.OnPressed += _ => OnBuy?.Invoke(catId, protoId, Shared._NC.CitiNet.Delivery.DropType.DeadDrop);
                
                buttonsBox.AddChild(buyCorpBtn);
                buttonsBox.AddChild(buyStreetBtn);
                
                hBox.AddChild(buttonsBox);
                row.AddChild(hBox);
                list.AddChild(row);
            }

            scroll.AddChild(list);
            Tabs.AddChild(scroll);
            Tabs.SetTabTitle(Tabs.ChildCount - 1, category.Name);
        }
    }
}

public sealed partial class FixerMarketUIFragment : UIFragment, ICitiNetSiteFragment
{
    private FixerMarketSiteUi? _control;

    public override Control GetUIFragmentRoot() => _control!;

    public override void Setup(BoundUserInterface userInterface, EntityUid? fragmentOwner)
    {
        _control = new FixerMarketSiteUi();
        _control.OnBuy += (catId, protoId, type) => userInterface.SendMessage(new CitiNetStoreBuyRequestMessage(catId, protoId, type));
        
        userInterface.SendMessage(new CitiNetStoreRequestDataMessage());
    }

    public override void UpdateState(BoundUserInterfaceState state)
    {
        if (state is CitiNetStoreUpdateState storeState)
            _control?.UpdateState(storeState);
    }

    public void ReceiveMessage(BoundUserInterfaceMessage message)
    {
    }
}
