using Content.Client.UserInterface.Fragments;
using Content.Shared._NC.Trade;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client._NC.CitiNet.UI.FixerMarket;

[GenerateTypedNameReferences]
public sealed partial class FixerMarketSiteUiFragment : PanelContainer
{
    private string? _selectedCategory;
    private FixerMarketStateMessage? _lastState;

    public event Action<string>? OnBuy;

    public FixerMarketSiteUiFragment()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(FixerMarketStateMessage state)
    {
        _lastState = state;
        BalanceLabel.Text = $"CREDITS: {state.Balance}";
        
        RefreshCategories(state.Categories);
        RefreshListings();
    }

    private void RefreshCategories(List<string> categories)
    {
        CategoryList.RemoveAllChildren();
        
        var allBtn = new Button { 
            Text = "ALL_ITEMS", 
            ToggleMode = true, 
            Pressed = _selectedCategory == null, 
            StyleClasses = { "FixerNavButton" } 
        };
        allBtn.OnPressed += _ => {
            _selectedCategory = null;
            RefreshCategories(categories);
            RefreshListings();
        };
        CategoryList.AddChild(allBtn);

        foreach (var category in categories)
        {
            var catBtn = new Button { 
                Text = category.ToUpper(), 
                ToggleMode = true, 
                Pressed = _selectedCategory == category,
                StyleClasses = { "FixerNavButton" }
            };
            var cat = category;
            catBtn.OnPressed += _ => {
                _selectedCategory = cat;
                RefreshCategories(categories);
                RefreshListings();
            };
            CategoryList.AddChild(catBtn);
        }
    }

    private void RefreshListings()
    {
        ListingsGrid.RemoveAllChildren();
        if (_lastState == null) return;

        foreach (var listing in _lastState.Listings)
        {
            if (_selectedCategory != null && listing.Category != _selectedCategory)
                continue;

            var panel = new PanelContainer { StyleClasses = { "FixerListing" }, MinSize = new Vector2(250, 140) };
            var vBox = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Vertical, Margin = new Thickness(8) };
            
            var nameLabel = new Label { Text = listing.Name.ToUpper(), StyleClasses = { "FixerItemName" }, HorizontalExpand = true, ClipText = true };
            vBox.AddChild(nameLabel);
            
            var descLabel = new Label { 
                Text = listing.Description, 
                FontColorOverride = Color.FromHex("#777777"), 
                VerticalExpand = true, 
                ClipText = true 
            };
            vBox.AddChild(descLabel);

            var footer = new BoxContainer { Orientation = BoxContainer.LayoutOrientation.Horizontal, Margin = new Thickness(0, 8, 0, 0) };
            
            var priceLabel = new Label { Text = $"{listing.Price} CR", StyleClasses = { "FixerItemPrice" }, HorizontalExpand = true };
            footer.AddChild(priceLabel);

            var buyBtn = new Button { 
                Text = "PURCHASE", 
                StyleClasses = { "FixerBuyButton" }, 
                MinWidth = 100 
            };
            var id = listing.Id;
            buyBtn.OnPressed += _ => OnBuy?.Invoke(id);
            footer.AddChild(buyBtn);

            vBox.AddChild(footer);
            panel.AddChild(vBox);
            ListingsGrid.AddChild(panel);
        }
    }
}

public sealed partial class FixerMarketUIFragment : UIFragment
{
    private FixerMarketSiteUiFragment? _control;

    public override Control GetUIFragmentRoot() => _control!;

    public override void Setup(BoundUserInterface userInterface, EntityUid? fragmentOwner)
    {
        _control = new FixerMarketSiteUiFragment();
        _control.OnBuy += (listingId) => userInterface.SendMessage(new FixerMarketBuyMessage(listingId, 1));
        
        userInterface.SendMessage(new FixerMarketRequestRefreshMessage());
    }

    public override void UpdateState(BoundUserInterfaceState state)
    {
        if (state is FixerMarketStateMessage fixerState)
            _control?.UpdateState(fixerState);
    }
}
