using Content.Client.UserInterface.Controls;
using Content.Shared._NC.LobbyRewards;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.LobbyRewards.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyRewardsWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public event Action<int, bool>? OnItemSelected;

    public LobbyRewardsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateState(LobbyRewardsEuiState state)
    {
        BalanceLabel.Text = state.NightCoinsBalance.ToString();

        InventoryContainer.DisposeAllChildren();

        foreach (var item in state.Inventory)
        {
            var itemControl = CreateItemControl(item);
            InventoryContainer.AddChild(itemControl);
        }
    }

    private Control CreateItemControl(LobbyRewardItem item)
    {
        var box = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(5),
            SeparationOverride = 10
        };

        var name = item.PrototypeId;
        if (_prototypeManager.TryIndex<EntityPrototype>(item.PrototypeId, out var proto))
        {
            name = proto.Name;
        }

        var label = new Label
        {
            Text = $"{name} (x{item.Quantity})",
            HorizontalExpand = true,
            VerticalAlignment = Control.VAlignment.Center
        };

        var checkBox = new CheckBox
        {
            Text = "DEPLOY",
            Pressed = item.Selected,
            VerticalAlignment = Control.VAlignment.Center
        };

        checkBox.OnToggled += args =>
        {
            OnItemSelected?.Invoke(item.Id, args.Pressed);
        };

        box.AddChild(label);
        box.AddChild(checkBox);

        var panel = new PanelContainer
        {
            StyleClasses = { "MenuMapInfo" }
        };
        panel.AddChild(box);

        return panel;
    }
}
