using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._NC.LobbyRewards;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._NC.LobbyRewards.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyRewardsWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IComponentFactory _componentFactory = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystemManager = default!;
    [Dependency] private readonly IResourceCache _resourceCache = default!;

    private SpriteSystem? _spriteSystem;
    private float _timer = 0f;
    private bool _glitchActive = false;
    private float _glitchTimer = 0f;

    public event Action<int, bool>? OnItemSelected;
    public event Action<string>? OnItemPurchase;
    public event Action? OnRefreshRequested;

    public LobbyRewardsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entitySystemManager.GetEntitySystem<SpriteSystem>();

        // Set textures (using existing nano textures as fallback)
        BackgroundGrid.Texture = _resourceCache.GetResource<TextureResource>("/Textures/Interface/Nano/stripeback.svg.96dpi.png");
        Scanlines.Texture = _resourceCache.GetResource<TextureResource>("/Textures/Interface/Nano/stripeback.svg.96dpi.png");
        Scanlines.Modulate = Color.White.WithAlpha(0.05f);

        RefreshButton.OnPressed += _ => OnRefreshRequested?.Invoke();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        _timer += args.DeltaSeconds;

        // Breathing background
        var alpha = 0.05f + (MathF.Sin(_timer * 0.5f) + 1f) * 0.05f;
        BackgroundGrid.Modulate = Color.FromHex("#00FF9D").WithAlpha(alpha);

        // Scanlines movement simulation
        var scanAlpha = 0.03f + (MathF.Sin(_timer * 8f) + 1f) * 0.02f;
        Scanlines.Modulate = Color.White.WithAlpha(scanAlpha);

        // HUD Time
        TimeLabel.Text = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss");

        if (_glitchActive)
        {
            _glitchTimer -= args.DeltaSeconds;
            if (_glitchTimer <= 0)
            {
                _glitchActive = false;
                GlitchOverlay.Visible = false;
            }
        }
    }

    private void TriggerGlitch(float duration = 0.08f)
    {
        _glitchActive = true;
        _glitchTimer = duration;
        GlitchOverlay.Visible = true;
    }

    public void UpdateState(LobbyRewardsEuiState state)
    {
        BalanceLabel.Text = $"{state.NightCoinsBalance:N0}";

        UpdateInventory(state.Inventory);
        UpdateMarket(state.MarketItems);
    }

    private void UpdateInventory(List<LobbyRewardItem> inventory)
    {
        InventoryGrid.DisposeAllChildren();

        if (inventory.Count == 0)
        {
            InventoryGrid.AddChild(CreateEmptyLabel("NO META-ITEMS IN STORAGE"));
            return;
        }

        foreach (var item in inventory)
        {
            InventoryGrid.AddChild(CreateItemCard(item));
        }
    }

    private void UpdateMarket(List<LobbyMarketItem> market)
    {
        MarketGrid.DisposeAllChildren();

        if (market.Count == 0)
        {
            MarketGrid.AddChild(CreateEmptyLabel("NIGHT-MARKET OFFLINE"));
            return;
        }

        foreach (var item in market)
        {
            MarketGrid.AddChild(CreateMarketCard(item));
        }
    }

    private Control CreateEmptyLabel(string text)
    {
        return new Label
        {
            Text = $"--- [ {text} ] ---",
            FontColorOverride = Color.FromHex("#ff3333"),
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 40)
        };
    }

    private Control CreateItemCard(LobbyRewardItem item)
    {
        var card = CreateBaseCard(item.PrototypeId);
        var content = (BoxContainer)card.GetChild(0);

        // Footer: Deployment Checkbox only (removed quantity)
        var footer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            Margin = new Thickness(0, 5, 0, 0)
        };
        
        footer.AddChild(new Control { HorizontalExpand = true });
        
        var deployCheck = new CheckBox
        {
            Text = "DEPLOY",
            Pressed = item.Selected,
            StyleClasses = { "ButtonColorGreen" }
        };
        deployCheck.OnToggled += args => OnItemSelected?.Invoke(item.Id, args.Pressed);
        footer.AddChild(deployCheck);
        
        content.AddChild(footer);
        card.OnMouseEntered += _ => UpdatePreview(item.PrototypeId);

        return card;
    }

    private Control CreateMarketCard(LobbyMarketItem item)
    {
        var card = CreateBaseCard(item.PrototypeId);
        var content = (BoxContainer)card.GetChild(0);

        // Price Tag
        var priceBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalAlignment = HAlignment.Center,
            Margin = new Thickness(0, 5)
        };
        priceBox.AddChild(new Label { 
            Text = $"{item.Price:N0} NC", 
            FontColorOverride = Color.FromHex("#00ffff"),
            StyleClasses = { "LabelHeading" }
        });
        content.AddChild(priceBox);

        // Buy Button
        var buyButton = new Button
        {
            Text = "BUY / EXTRACT",
            StyleClasses = { "ButtonColorGreen" },
            HorizontalExpand = true
        };
        buyButton.OnPressed += _ => OnItemPurchase?.Invoke(item.PrototypeId);
        content.AddChild(buyButton);

        card.OnMouseEntered += _ => UpdatePreview(item.PrototypeId);

        return card;
    }

    private PanelContainer CreateBaseCard(string protoId)
    {
        var card = new PanelContainer
        {
            StyleClasses = { "Inset" },
            MinWidth = 200,
            MinHeight = 160,
            MouseFilter = MouseFilterMode.Stop,
            ToolTip = protoId
        };

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(10),
            SeparationOverride = 6
        };

        string name = protoId;
        string rarity = "COMMON";
        Color rarityColor = Color.FromHex("#bbbbbb");

        if (_prototypeManager.TryIndex<EntityPrototype>(protoId, out var proto))
        {
            name = proto.Name;
            if (proto.TryGetComponent<NcRewardMetadataComponent>(out var metadata, _componentFactory))
            {
                rarity = metadata.Rarity;
                rarityColor = GetColorForRarity(rarity);
            }

            // Sprite
            var spriteContainer = new PanelContainer
            {
                MinHeight = 80,
                PanelOverride = new StyleBoxFlat { BackgroundColor = Color.Black.WithAlpha(0.4f) },
                HorizontalAlignment = HAlignment.Center
            };
            
            if (_spriteSystem != null)
            {
                spriteContainer.AddChild(new TextureRect
                {
                    Texture = _spriteSystem.Frame0(proto),
                    SetSize = new Vector2(64, 64),
                    Stretch = TextureRect.StretchMode.KeepAspectCentered,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center
                });
            }
            content.AddChild(spriteContainer);
        }

        // Title
        content.AddChild(new Label
        {
            Text = name.ToUpper(),
            StyleClasses = { "LabelSubtext" },
            FontColorOverride = rarityColor,
            HorizontalAlignment = HAlignment.Center,
            ClipText = true
        });

        // Badges: Rarity only (removed Source/Brand)
        var badgeBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            SeparationOverride = 4,
            HorizontalAlignment = HAlignment.Center
        };
        badgeBox.AddChild(CreateBadge(rarity, rarityColor));
        content.AddChild(badgeBox);

        card.AddChild(content);

        // Hover animation (Removed TriggerGlitch as requested)
        card.OnMouseEntered += _ => {
            card.Modulate = Color.White.WithAlpha(1.2f);
        };
        card.OnMouseExited += _ => {
            card.Modulate = Color.White;
        };

        return card;
    }

    private Control CreateBadge(string text, Color color)
    {
        var badge = new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = color.WithAlpha(0.15f),
                BorderColor = color,
                BorderThickness = new Thickness(1)
            }
        };

        badge.AddChild(new Label
        {
            Text = text,
            Margin = new Thickness(8, 2),
            FontColorOverride = color
        });

        return badge;
    }

    private Color GetColorForRarity(string rarity)
    {
        return rarity.ToUpper() switch
        {
            "UNCOMMON" => Color.FromHex("#1eff00"),
            "RARE" => Color.FromHex("#0070dd"),
            "ICONIC" => Color.FromHex("#a335ee"),
            "LEGENDARY" => Color.FromHex("#ff8000"),
            _ => Color.FromHex("#ffffff")
        };
    }

    private void UpdatePreview(string protoId)
    {
        PreviewContainer.DisposeAllChildren();
        
        if (!_prototypeManager.TryIndex<EntityPrototype>(protoId, out var proto))
            return;

        PreviewContainer.AddChild(new Label { 
            Text = proto.Name.ToUpper(), 
            StyleClasses = { "LabelHeading" },
            HorizontalAlignment = HAlignment.Center
        });
        
        PreviewContainer.AddChild(new PanelContainer { MinHeight = 2, StyleClasses = { "LowDivider" } });
        
        var scroll = new ScrollContainer { VerticalExpand = true, HorizontalExpand = true };
        var desc = new RichTextLabel { Margin = new Thickness(0, 5) };
        desc.SetMessage(proto.Description);
        scroll.AddChild(desc);
        PreviewContainer.AddChild(scroll);

        if (proto.TryGetComponent<NcRewardMetadataComponent>(out var metadata, _componentFactory))
        {
            PreviewContainer.AddChild(new Label { 
                Text = $"> SECURITY_RATING: {metadata.Rarity}", 
                StyleClasses = { "LabelSubtext" }, 
                Modulate = Color.White.WithAlpha(0.6f) 
            });
        }

        var scanning = new Label { 
            Text = "DATA_EXTRACTED_SUCCESSFULLY", 
            HorizontalAlignment = HAlignment.Center,
            FontColorOverride = Color.FromHex("#00ff9d"),
            StyleClasses = { "LabelSubtext" }
        };
        PreviewContainer.AddChild(scanning);
    }
}
