using System.Linq;
using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._NC.LobbyRewards;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._NC.LobbyRewards.UI;

[GenerateTypedNameReferences]
public sealed partial class LobbyRewardsWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IComponentFactory _componentFactory = default!;
    [Dependency] private readonly IEntitySystemManager _entitySystemManager = default!;

    private SpriteSystem? _spriteSystem;

    // ── Events ───────────────────────────────────────────────────────────────
    public event Action<int, bool>? OnItemSelected;
    public event Action<string>? OnItemPurchase;
    public event Action? OnRefreshRequested;
    public event Action? OnResetLoadout;

    // ── Local state ──────────────────────────────────────────────────────────
    private bool _isMarketView;
    private string _activeCategory = "All";
    private LobbyRewardsEuiState? _lastState;

    // ── Color palette ────────────────────────────────────────────────────────
    private static readonly Color ColorNeonGreen = Color.FromHex("#00FF9D");
    private static readonly Color ColorNeonCyan = Color.FromHex("#00FFFF");
    private static readonly Color ColorNeonRed = Color.FromHex("#F85149");
    private static readonly Color ColorCardBg = Color.FromHex("#161B22");
    private static readonly Color ColorCardBorder = Color.FromHex("#30363D");
    private static readonly Color ColorBgDark = Color.FromHex("#0D1117");
    private static readonly Color ColorTextPrimary = Color.FromHex("#C9D1D9");
    private static readonly Color ColorTextSecondary = Color.FromHex("#8B949E");
    private static readonly Color ColorActiveTab = Color.FromHex("#1F6FEB");

    public LobbyRewardsWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _spriteSystem = _entitySystemManager.GetEntitySystem<SpriteSystem>();


        // ── Wire tab buttons ─────────────────────────────────────────────────
        StorageTabButton.OnPressed += _ => SwitchToStorage();
        MarketTabButton.OnPressed += _ => SwitchToMarket();

        // ── Action buttons ───────────────────────────────────────────────────
        ResetLoadoutButton.OnPressed += _ => OnResetLoadout?.Invoke();
        SaveLoadoutButton.OnPressed += _ => OnRefreshRequested?.Invoke(); // Save = just confirm (already saved per-click)

        // Default to storage view
        SwitchToStorage();
    }



    // ── Tab switching ────────────────────────────────────────────────────────

    private void SwitchToStorage()
    {
        _isMarketView = false;
        StoragePanel.Visible = true;
        MarketPanel.Visible = false;

        // Highlight active tab
        StorageTabButton.Modulate = Color.White;
        MarketTabButton.Modulate = Color.White.WithAlpha(0.6f);

        if (_lastState != null)
            UpdateState(_lastState);
    }

    private void SwitchToMarket()
    {
        _isMarketView = true;
        StoragePanel.Visible = false;
        MarketPanel.Visible = true;

        StorageTabButton.Modulate = Color.White.WithAlpha(0.6f);
        MarketTabButton.Modulate = Color.White;

        if (_lastState != null)
            UpdateState(_lastState);
    }



    // ── Main state update ────────────────────────────────────────────────────

    public void UpdateState(LobbyRewardsEuiState state)
    {
        _lastState = state;


        // Market balance
        MarketBalanceLabel.Text = $" {state.NightCoinsBalance:N0} NC";

        if (!_isMarketView)
        {
            UpdateCategories(state.Inventory);
            UpdateInventory(state.Inventory);
            UpdateLoadoutSidebar(state.Inventory);
        }
        else
        {
            UpdateMarket(state.MarketItems, state.NightCoinsBalance, state.Inventory);
        }
    }

    // ── Category sidebar (Storage tab) ───────────────────────────────────────

    private void UpdateCategories(List<LobbyRewardItem> inventory)
    {
        CategoryButtons.DisposeAllChildren();

        // "All" category
        var allButton = CreateCategoryButton("Все", "All", inventory.Count);
        CategoryButtons.AddChild(allButton);

        // Unique categories from inventory
        var categories = inventory
            .Select(x => x.Category)
            .Distinct()
            .OrderBy(x => x)
            .ToList();

        foreach (var cat in categories)
        {
            var count = inventory.Count(x => x.Category == cat);
            CategoryButtons.AddChild(CreateCategoryButton(GetCategoryDisplayName(cat), cat, count));
        }
    }

    private Button CreateCategoryButton(string displayName, string categoryId, int count)
    {
        var btn = new Button
        {
            Text = $"{displayName} ({count})",
            HorizontalExpand = true,
            MinHeight = 30,
            ClipText = true,
            Modulate = _activeCategory == categoryId ? Color.White : Color.White.WithAlpha(0.5f),
        };

        btn.OnPressed += _ =>
        {
            _activeCategory = categoryId;
            if (_lastState != null)
                UpdateState(_lastState);
        };

        return btn;
    }

    private static string GetCategoryDisplayName(string category)
    {
        return category switch
        {
            "Armor" => "Броня",
            "Weapons" => "Оружие",
            "Medicine" => "Медицина",
            "Upgrades" => "Улучшения",
            "Skins" => "Скины",
            "Misc" => "Разное",
            _ => category
        };
    }

    // ── Inventory grid (Storage tab) ─────────────────────────────────────────

    private void UpdateInventory(List<LobbyRewardItem> inventory)
    {
        InventoryGrid.DisposeAllChildren();

        var filtered = _activeCategory == "All"
            ? inventory
            : inventory.Where(x => x.Category == _activeCategory).ToList();

        if (filtered.Count == 0)
        {
            InventoryGrid.AddChild(new Label
            {
                Text = "--- [ ХРАНИЛИЩЕ ПУСТО ] ---",
                FontColorOverride = ColorNeonRed,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 40),
            });
            return;
        }

        foreach (var item in filtered)
        {
            InventoryGrid.AddChild(CreateStorageCard(item));
        }
    }

    private Control CreateStorageCard(LobbyRewardItem item)
    {
        // Outer card container
        var card = new PanelContainer
        {
            MinWidth = 180,
            MinHeight = 140,
            MouseFilter = MouseFilterMode.Stop,
        };
        card.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = item.Selected ? ColorCardBg.WithAlpha(0.95f) : ColorCardBg.WithAlpha(0.7f),
            BorderColor = item.Selected ? ColorNeonGreen : ColorCardBorder,
            BorderThickness = new Thickness(item.Selected ? 2 : 1),
        };

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(8),
            SeparationOverride = 4,
        };

        // Sprite
        if (_prototypeManager.TryIndex<EntityPrototype>(item.PrototypeId, out var proto) && _spriteSystem != null)
        {
            var spriteRect = new TextureRect
            {
                Texture = _spriteSystem.Frame0(proto),
                SetSize = new Vector2(48, 48),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
            };
            content.AddChild(spriteRect);

            // Name
            content.AddChild(new Label
            {
                Text = proto.Name.ToUpper(),
                FontColorOverride = GetColorForRarity(GetRarity(item.PrototypeId)),
                HorizontalAlignment = HAlignment.Center,
                ClipText = true,
                StyleClasses = { "LabelSubtext" },
            });
        }
        else
        {
            content.AddChild(new Label
            {
                Text = item.PrototypeId,
                FontColorOverride = ColorTextSecondary,
                HorizontalAlignment = HAlignment.Center,
                ClipText = true,
            });
        }

        // Points cost badge (top-right style)
        if (item.PointsCost > 0)
        {
            content.AddChild(new Label
            {
                Text = $"{item.PointsCost} ОЧК",
                FontColorOverride = ColorNeonCyan,
                HorizontalAlignment = HAlignment.Right,
                StyleClasses = { "LabelSubtext" },
            });
        }

        // Add/Remove button
        var actionBtn = new Button
        {
            Text = item.Selected ? "УБРАТЬ" : "ДОБАВИТЬ",
            HorizontalExpand = true,
            MinHeight = 26,
            StyleClasses = { item.Selected ? "ButtonColorRed" : "ButtonColorGreen" },
        };
        actionBtn.OnPressed += _ => OnItemSelected?.Invoke(item.Id, !item.Selected);
        content.AddChild(actionBtn);

        card.AddChild(content);

        // Hover effect
        card.OnMouseEntered += _ =>
        {
            if (card.PanelOverride is StyleBoxFlat sb)
                sb.BorderColor = ColorNeonGreen;
        };
        card.OnMouseExited += _ =>
        {
            if (card.PanelOverride is StyleBoxFlat sb)
                sb.BorderColor = item.Selected ? ColorNeonGreen : ColorCardBorder;
        };

        return card;
    }

    // ── Loadout sidebar ("МОЯ СБОРКА") ───────────────────────────────────────

    private void UpdateLoadoutSidebar(List<LobbyRewardItem> inventory)
    {
        LoadoutList.DisposeAllChildren();

        var selected = inventory.Where(x => x.Selected).ToList();

        if (selected.Count == 0)
        {
            LoadoutList.AddChild(new Label
            {
                Text = "Пусто",
                FontColorOverride = ColorTextSecondary,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 20),
                StyleClasses = { "LabelSubtext" },
            });
            return;
        }

        foreach (var item in selected)
        {
            var row = new PanelContainer
            {
                MinHeight = 44,
            };
            row.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = ColorBgDark.WithAlpha(0.8f),
                BorderColor = ColorCardBorder,
                BorderThickness = new Thickness(0, 0, 0, 1),
            };

            var rowContent = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                Margin = new Thickness(6, 2),
                SeparationOverride = 6,
            };

            // Small sprite
            if (_prototypeManager.TryIndex<EntityPrototype>(item.PrototypeId, out var proto) && _spriteSystem != null)
            {
                rowContent.AddChild(new TextureRect
                {
                    Texture = _spriteSystem.Frame0(proto),
                    SetSize = new Vector2(32, 32),
                    Stretch = TextureRect.StretchMode.KeepAspectCentered,
                    VerticalAlignment = VAlignment.Center,
                });

                rowContent.AddChild(new Label
                {
                    Text = proto.Name,
                    FontColorOverride = ColorTextPrimary,
                    VerticalAlignment = VAlignment.Center,
                    HorizontalExpand = true,
                    ClipText = true,
                    StyleClasses = { "LabelSubtext" },
                });
            }

            // Points cost
            if (item.PointsCost > 0)
            {
                rowContent.AddChild(new Label
                {
                    Text = $"{item.PointsCost}",
                    FontColorOverride = ColorNeonCyan,
                    VerticalAlignment = VAlignment.Center,
                    StyleClasses = { "LabelSubtext" },
                });
            }

            row.AddChild(rowContent);
            LoadoutList.AddChild(row);
        }
    }

    // ── Market grid ──────────────────────────────────────────────────────────

    private void UpdateMarket(List<LobbyMarketItem> market, int balance, List<LobbyRewardItem> inventory)
    {
        MarketGrid.DisposeAllChildren();
        ClearPreview();

        if (market.Count == 0)
        {
            MarketGrid.AddChild(new Label
            {
                Text = "--- [ НЕТ ТОВАРОВ ] ---",
                FontColorOverride = ColorNeonRed,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 40),
            });
            return;
        }

        // Build a set of owned prototype IDs for fast lookup
        var ownedProtos = new HashSet<string>(inventory.Select(x => x.PrototypeId));

        foreach (var item in market)
        {
            MarketGrid.AddChild(CreateMarketCard(item, balance, ownedProtos));
        }
    }

    private Control CreateMarketCard(LobbyMarketItem item, int balance, HashSet<string> ownedProtos)
    {
        var alreadyOwned = ownedProtos.Contains(item.PrototypeId);
        var card = new PanelContainer
        {
            MinWidth = 150,
            MinHeight = 150,
            MouseFilter = MouseFilterMode.Stop,
        };
        card.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = ColorCardBg.WithAlpha(0.8f),
            BorderColor = alreadyOwned ? ColorNeonGreen : ColorCardBorder,
            BorderThickness = new Thickness(1),
        };

        var content = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(8),
            SeparationOverride = 4,
        };

        // Sprite
        if (_prototypeManager.TryIndex<EntityPrototype>(item.PrototypeId, out var proto) && _spriteSystem != null)
        {
            var spriteRect = new TextureRect
            {
                Texture = _spriteSystem.Frame0(proto),
                SetSize = new Vector2(48, 48),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
            };
            content.AddChild(spriteRect);

            content.AddChild(new Label
            {
                Text = proto.Name.ToUpper(),
                FontColorOverride = GetColorForRarity(GetRarity(item.PrototypeId)),
                HorizontalAlignment = HAlignment.Center,
                ClipText = true,
                StyleClasses = { "LabelSubtext" },
            });
        }

        // Price
        var canAfford = balance >= item.Price;
        content.AddChild(new Label
        {
            Text = $"{item.Price:N0} NC",
            FontColorOverride = alreadyOwned ? ColorTextSecondary : (canAfford ? ColorNeonCyan : ColorNeonRed),
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = { "LabelSubtext" },
        });

        // Buy button — disabled if already owned or can't afford
        var buyBtn = new Button
        {
            Text = alreadyOwned ? "КУПЛЕНО" : "КУПИТЬ",
            HorizontalExpand = true,
            MinHeight = 26,
            Disabled = alreadyOwned || !canAfford,
            StyleClasses = { alreadyOwned ? "ButtonColorCaution" : "ButtonColorGreen" },
        };
        buyBtn.OnPressed += _ => OnItemPurchase?.Invoke(item.PrototypeId);
        content.AddChild(buyBtn);

        card.AddChild(content);

        // Hover: highlight + show description
        card.OnMouseEntered += _ =>
        {
            if (card.PanelOverride is StyleBoxFlat sb)
                sb.BorderColor = ColorNeonCyan;
            UpdatePreview(item.PrototypeId, item.Price);
        };
        card.OnMouseExited += _ =>
        {
            if (card.PanelOverride is StyleBoxFlat sb)
                sb.BorderColor = ColorCardBorder;
        };

        return card;
    }


    // ── Description/Preview panel ────────────────────────────────────────────

    private void ClearPreview()
    {
        PreviewContent.DisposeAllChildren();
        PreviewContent.AddChild(new Label
        {
            Text = "Наведите на предмет для просмотра описания.",
            FontColorOverride = ColorTextSecondary,
            StyleClasses = { "LabelSubtext" },
        });
    }

    private void UpdatePreview(string protoId, int price)
    {
        PreviewContent.DisposeAllChildren();

        if (!_prototypeManager.TryIndex<EntityPrototype>(protoId, out var proto))
            return;

        // Sprite preview
        if (_spriteSystem != null)
        {
            PreviewContent.AddChild(new TextureRect
            {
                Texture = _spriteSystem.Frame0(proto),
                MinSize = new Vector2(64, 64),
                SetSize = new Vector2(64, 64),
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 4),
            });
        }

        // Name
        PreviewContent.AddChild(new Label
        {
            Text = proto.Name.ToUpper(),
            FontColorOverride = ColorTextPrimary,
            HorizontalAlignment = HAlignment.Center,
            StyleClasses = { "LabelHeading" },
        });

        // Price
        PreviewContent.AddChild(new Label
        {
            Text = $"Цена: {price:N0} NC",
            FontColorOverride = ColorNeonCyan,
            HorizontalAlignment = HAlignment.Center,
        });

        // Divider
        var divider = new PanelContainer { MinHeight = 1 };
        divider.PanelOverride = new StyleBoxFlat { BackgroundColor = ColorCardBorder };
        PreviewContent.AddChild(divider);

        // Description (wrapped in RichTextLabel for word wrapping)
        if (!string.IsNullOrEmpty(proto.Description))
        {
            var desc = new RichTextLabel
            {
                Margin = new Thickness(0, 4),
            };
            desc.SetMessage(proto.Description);
            PreviewContent.AddChild(desc);
        }

        // Rarity
        if (proto.TryGetComponent<NcRewardMetadataComponent>(out var metadata, _componentFactory))
        {
            PreviewContent.AddChild(new Label
            {
                Text = $"Класс: {metadata.Rarity}",
                FontColorOverride = GetColorForRarity(metadata.Rarity),
                StyleClasses = { "LabelSubtext" },
            });
        }
    }

    // ── Helpers ───────────────────────────────────────────────────────────────

    private string GetRarity(string protoId)
    {
        if (_prototypeManager.TryIndex<EntityPrototype>(protoId, out var proto) &&
            proto.TryGetComponent<NcRewardMetadataComponent>(out var metadata, _componentFactory))
        {
            return metadata.Rarity;
        }
        return "COMMON";
    }

    private static Color GetColorForRarity(string rarity)
    {
        return rarity.ToUpper() switch
        {
            "UNCOMMON" => Color.FromHex("#1EFF00"),
            "RARE" => Color.FromHex("#0070DD"),
            "ICONIC" => Color.FromHex("#A335EE"),
            "LEGENDARY" => Color.FromHex("#FF8000"),
            _ => Color.FromHex("#C9D1D9"),
        };
    }
}
